---
run:
  deadline: 5m
  tests: false

linters-settings:

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "Binds to all network interfaces"
      linters:
        - gosec
